### ISSUE TITLE
Unlocking New World (Full Grid) (3)

### ISSUE THREAD

**Issue by kvanorny** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_004#11]
As a user who has uncovered all grid regions 

So that I can continue playing the game 

I want to be provided a new grid, with locked regions to allow continued play

**Comment by samanthapoth** [comment]
I am working on this and will finish tomorrow, 11/29. Currently, all of the API calls are working, just refining the output to have a cleaner world map.

**Comment by samanthapoth** [comment]
Working on completion logic then will add restart world button.

**Comment by samanthapoth** [comment]
completed
