### ISSUE TITLE
User Unlocks a Grid Space via Puzzle (6)

### ISSUE THREAD

**Issue by kvanorny** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_004#20]
As a current user who is in one grid space
So I can move to a neighboring tile
I want to be able to complete a mini puzzle to unlock the neighboring tile

**Comment by kvanorny** [comment]
Update on UC: Mini game is functional with one small bug and it is successfully passing a true/false boolean whether they win or lose. Once the bug is fixed this will be fully functional

**Comment by samanthapoth** [comment]
Minigame fixed flipping and redirecting to landing page.
